# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0002_carosel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='harga',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stone',
            name='size',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
