# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0003_auto_20160819_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carosel',
            name='stone',
        ),
        migrations.AddField(
            model_name='carosel',
            name='stone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stones.Stone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stone',
            name='cover_stone',
            field=models.FileField(upload_to='stones'),
        ),
    ]
