# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0004_auto_20160827_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stones.Stone')),
            ],
        ),
    ]
