# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0005_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='cover_stone',
            field=models.ImageField(upload_to='{{ MEDIA_URL }}stones'),
        ),
    ]
