# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0006_auto_20160827_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carosel',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='produk',
            name='deskripsi',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stone',
            name='cover_stone',
            field=models.ImageField(upload_to='stones'),
        ),
    ]
