# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0007_auto_20160830_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carosel',
            name='stone',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='stone',
        ),
        migrations.AddField(
            model_name='stone',
            name='depan',
            field=models.BooleanField(default='False'),
        ),
        migrations.DeleteModel(
            name='carosel',
        ),
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
