# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import stones.models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0009_auto_20160908_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='nama_kategori',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='deskripsi',
        ),
        migrations.AlterField(
            model_name='stone',
            name='cover_stone',
            field=models.ImageField(max_length=256, upload_to=stones.models.get_file_path),
        ),
    ]
