# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-24 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0011_auto_20160924_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stone',
            old_name='cover_stone',
            new_name='image',
        ),
    ]
